# TODOs

- office/reflection.md:
  - description: No TODO markers left in reflection.md
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- builder/data_creator.py:
  - description: No TODO markers left in data_creator.py
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- builder/table_builder.py:
  - description: No TODO markers left in table_builder.py
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- arranger/table_arranger.py:
  - description: No TODO markers left in table_arranger.py
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true
- analyzer/table_analyzer.py:
  - description: No TODO markers left in table_analyzer.py
    check: MatchFileFragment
    options:
      fragment: "TODO"
      count: 0
      exact: true

# Existential file crisis
- builder/data/registry.csv:
  - description: registry.csv file exists in builder/data/registry.csv
    check: ConfirmFileExists
- builder/data/registry.csv:
  - description: table columns are in the order requested by the README
    check: MatchFileRegex
    options:
      regex: '[ID|id|Id],[N|n]eighborhood,[N|n]ame'
      count: 1
      exact: true

# Reflection data

- office/reflection.md:
  - description: All questions answered in reflection.md
    check: CountFileParagraphs
    options:
      count: 6
      exact: false

# Code cops

# lists
- builder/data_creator.py:
  - description: builder/data_creator.py creates an additional empty list
    check: MatchFileRegex
    options:
      regex: '=(\s)?\[\]'
      count: 2
      exact: true
- builder/data_creator.py:
  - description: builder/data_creator.py features a list that uses the .append method
    check: MatchFileRegex
    options:
      regex: '\.append\([a-zA-Z0-9_]+\)'
      count: 1
      exact: true
- builder/data_creator.py:
  - description: builder/data_creator.py features a list that uses add_names function
    check: MatchFileRegex
    options:
      regex: 'add_names\([a-zA-Z0-9_]+\)'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py uses the DATA list to add to table
    check: MatchFileRegex
    options:
      regex: 'DATA\[[a-zA-Z0-9\-\s_]+\]'
      count: 1
      exact: false
- builder/table_builder.py:
  - description: builder/table_builder.py appends to the COLS variable when adding columns
    check: MatchFileRegex
    options:
        regex: 'COLS\.append\([a-zA-Z0-9_]+\)'
        count: 1
        exact: false
- builder/table_builder.py:
  - description: builder/table_builder.py uses the pop() method to remove from row and/or column
    check: MatchFileRegex
    options:
        regex: '\.pop\(\)'
        count: 1
        exact: false
- arranger/table_arranger.py:
  - description: arranger/table_arranger.py uses the index method to retrieve list addresses
    check: MatchFileRegex
    options:
      regex: '\.index\([a-zA-Z0-9_]+\)'
      count: 3
      exact: false
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py uses the len() function to compute averages
    check: MatchFileRegex
    options:
      regex: 'len\([a-zA-Z0-9_]+\)'
      count: 1
      exact: false

# Iteration

- arranger/table_arranger.py:
  - description: arranger/table_arranger.py uses a for loop with the DATA variable to switch columns
    check: MatchFileRegex
    options:
      regex: 'for [a-zA-Z0-9_]+ in DATA\:'
      count: 1
      exact: false
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py uses for loops with the DATA variable to discover data
    check: MatchFileRegex
    options:
      regex: 'for [a-zA-Z0-9_]+ in DATA\:'
      count: 3
      exact: false

# functions
- builder/table_builder.py:
  - description: builder/table_builder.py implements a function called add_column with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def add_column\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py calls add_column with 1 argument
    check: MatchFileRegex
    options:
      regex: 'add_column\([a-zA-Z0-9_]+\)(?!(\s)?\:)'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py implements a function called get_row with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def get_row\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py calls add_column with 1 argument
    check: MatchFileRegex
    options:
      regex: 'get_row\([a-zA-Z0-9_]+\)(?!(\s)?\:)'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py implements a function called add_to_row with 2 parameters
    check: MatchFileRegex
    options:
      regex: 'def add_to_row\([a-zA-Z0-9_\:\s"=]+,(\s)?[a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py calls add_to_row with 2 arguments
    check: MatchFileRegex
    options:
      regex: 'add_to_row\([a-zA-Z0-9_]+,(\s)?[a-zA-Z0-9_]+\)'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py implements a function called remove_from_row with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def remove_from_row\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
      exact: true
- builder/table_builder.py:
  - description: builder/table_builder.py calls add_column with 1 argument
    check: MatchFileRegex
    options:
      regex: 'add_column\([a-zA-Z0-9_]+\)(?!(\s)?\:)'
      count: 1
      exact: true
- arranger/table_arranger.py:
  - description: arranger/table_arranger.py implements a switch_columns function with 2 parameters
    check: MatchFileRegex
    options:
      regex: 'def switch_columns(\s)?\([a-zA-Z0-9_\:\s"=]+,(\s)?[a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
- arranger/table_arranger.py:
  - description: arranger/table_arranger.py calls switch_columns with 2 arguments
    check: MatchFileRegex
    options:
      regex: 'switch_columns\([a-zA-Z0-9_]+,(\s)?[a-zA-Z0-9_]+\)'
      count: 1
      exact: true
- arranger/table_arranger.py:
  - description: arranger/table_arranger.py calls the sorter function with one argument
    check: MatchFileRegex
    options:
      regex: 'sorter\([a-zA-Z0-9_]+\)'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py implements a counter function with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def counter(\s)?\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py calls the counter function with one argument
    check: MatchFileRegex
    options:
      regex: 'counter\([a-zA-Z0-9_]+\)'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py implements a avg_column function with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def avg_column(\s)?\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py calls the avg_column function with one argument
    check: MatchFileRegex
    options:
      regex: 'avg_column\([a-zA-Z0-9_]+\)'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py implements a max_value function with 1 parameter
    check: MatchFileRegex
    options:
      regex: 'def max_value(\s)?\([a-zA-Z0-9_\:\s"=]+\)(.*)?\:'
      count: 1
- analyzer/table_analyzer.py:
  - description: analyzer/table_analyzer.py calls the max_value function with one argument
    check: MatchFileRegex
    options:
      regex: 'max_value\([a-zA-Z0-9_]+\)'
      count: 1